"""
Object Classes for Annotation Tool
------------------------------------
Define your custom object classes here.
The annotation tool will use this list for the class dropdown.

If this file is not present, the tool will use default classes
from COCO_CLASSES.py or a basic set of common objects.
"""

# Example: Indoor/Business objects
OBJECT_CLASSES = [
    
    "beds",
    "mattresses",
    "pillows",
    "blankets",
    "comforters",
    "bedding sets",
    "towels and washcloths",
    "nightstands",
    "dressers",
    "sofa sleeper",
    "air mattress",
    "trundle bed",
    "messy bed",
    "made bed",
    "sheets",
    "pillowcases",
    "comforter",
    "lamp",
    "alarm clock",
    "clothes hangers",
    "mirror",
    "laundry hamper",
    "decorative pillows",
    "couch",
    "sofa",
    "armchairs",
    "coffee table",
    "side tables",
    "rug",
    "television",
    "tv screens",
    "tv remotes",
    "remote",
    "other remote controls",
    "books",
    "magazines",
    "wall art",
    "curtains",
    "blinds",
    "throw blankets",
    "pillows and decor items",
    "wi-fi router",
    "coasters",
    "dining table",
    "dining chairs",
    "centerpiece",
    "kitchen sink",
    "oven",
    "microwave",
    "refrigerator",
    "freezer",
    "dishwasher",
    "stove",
    "toaster",
    "coffee maker",
    "electric kettle",
    "blender",
    "coffee container",
    "sugar container",
    "paper towel roll",
    "paper towel",
    "dish soap",
    "sponges",
    "trash bags",
    "aluminum foil",
    "plastic wrap",
    "kitchen trash can",
    "toilet",
    "toilet seat",
    "toilet lid",
    "toilet paper roll",
    "toilet paper",
    "hand towels",
    "bath mat",
    "shower curtain",
    "shower liner",
    "hand soap",
    "shampoo",
    "conditioner",
    "hair dryer",
    "plunger",
    "toilet brush",
    "tissues",
    "trash can",
    "first aid kit",
    "entry rugs",
    "welcome mat",
    "washer",
    "dryer",
    "lint trap",
    "laundry bags",
    "piles of linens",
    "laundry detergent",
    "dryer sheets",
    "ironing board",
    "drying rack",
    "folded linens",
    "laundry (not in machine)",
    "paper towels",
    "soap",
    "coffee supplies",
    "extra linens",
    "extra blankets",
    "storage bins",
    "cleaning sprays",
    "disinfectant wipes",
    "tvs",
    "other remotes",
    "lamps",
    "table",
    "chairs",
    "loungers",
    "grill",
    "umbrella",
    "garden hose",
    "decor",
    "vase",
    "bowl",
    "decorative pillow",
    "broom",
    "dustpan",
    "stains",
    "chipping damage",
    "ripping damage",
    "cracked damage",
    "grime",
    "fresh trashcan",
    "used trashcan",
]