"""
Object Classes for Annotation Tool
------------------------------------
Define your custom object classes here.
The annotation tool will use this list for the class dropdown.

If this file is not present, the tool will use default classes
from COCO_CLASSES.py or a basic set of common objects.
"""

# Example: Indoor/Business objects
OBJECT_CLASSES = [
    
    "bed",
    "pillow",
    "comforter",
    "towel",
    "washcloth",
    "nightstand",
    "dresser",
    "sofa sleeper",
    "air mattress",
    "trundle bed",
    "messy bed",
    "made bed",
    "sheet",
    "lamp",
    "alarm clock",
    "clothes hanger",
    "mirror",
    "laundry hamper",
    "couch",
    "sofa",
    "armchair",
    "coffee table",
    "side table",
    "rug",
    "television",
    "tv remote",
    "book",
    "magazine",
    "wall art",
    "curtain",
    "blinds",
    "decor item",
    "wi-fi router",
    "coaster",
    "dining table",
    "dining chair",
    "centerpiece",
    "kitchen sink",
    "oven",
    "microwave",
    "refrigerator",
    "freezer",
    "dishwasher",
    "stove",
    "toaster",
    "coffee maker",
    "electric kettle",
    "blender",
    "coffee container",
    "sugar container",
    "paper towel roll",
    "paper towel",
    "dish soap",
    "sponge",
    "trash bag",
    "aluminum foil",
    "plastic wrap",
    "toilet",
    "toilet seat",
    "toilet lid",
    "toilet paper roll",
    "toilet paper",
    "hand towel",
    "bath mat",
    "shower curtain",
    "shower liner",
    "hand soap",
    "shampoo",
    "conditioner",
    "hair dryer",
    "plunger",
    "toilet brush",
    "tissue box",
    "trash can",
    "first aid kit",
    "entry rug",
    "welcome mat",
    "washer",
    "dryer",
    "lint trap",
    "laundry bag",
    "piles of linens",
    "laundry detergent",
    "dryer sheets",
    "ironing board",
    "drying rack",
    "folded linens",
    "laundry",
    "paper towels",
    "coffee supplies",
    "linens",
    "blanket",
    "storage bin",
    "cleaning spray",
    "disinfectant wipe",
    "table",
    "chair",
    "lounger",
    "grill",
    "umbrella",
    "garden hose",
    "decor",
    "vase",
    "bowl",
    "decorative pillow",
    "broom",
    "dustpan",
    "stain",
    "chipping damage",
    "ripping damage",
    "cracked damage",
    "grime",
    "fresh trashcan",
    "used trashcan",
]